name: Build and Deploy Sphinx Docs

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - run: mv .github/requirements.txt docs/

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: Build PDF
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v2
      with:
        name: Documentation
        path: docs/build/latex/materials-modelling.pdf

    - run: sudo touch docs/build/html/.nojekyll
    - run: sudo mv docs/build/latex/materials-modelling.pdf docs/build/html/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html/
        CLEAN: true # Automatically remove deleted files from the deploy branch
